### Deploy pantheon branch to Pantheon dev environment

name: Dev Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - pantheon

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BUILD_FOLDER: ./build
      DEPLOY_FOLDER: ./deploy
      DEPLOY_REPO: ${{ secrets.DEV_DEPLOY_REPO }}
      SERVER_TYPE: Development
      INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_WEBHOOK }}

    steps:
      ### Setup

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Slack notification
        uses: tokorom/action-slack-incoming-webhook@v1.1.4
        with:
          blocks: |
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Deploy to Pantheon"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repo*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch*\n${{ steps.extract_branch.outputs.branch }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Initiated by*\n${{ github.actor }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Initiating event*\n${{ github.event_name }}"
                  }
                ]
              }
            ]

      ### Deploy

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: codeserver.dev.5dfa8617-1517-4b36-9369-893e98466d05.drush.in
          config: |
            Host *.drush.in
                User git
                IdentityFile ~/.ssh/id_rsa
                ForwardAgent yes
                StrictHostKeyChecking no

      - name: Checkout development repo
        uses: actions/checkout@v2
        with:
          path: ${{ env.BUILD_FOLDER }}
          ref: ${{ github.ref }}

      # ssh-keyscan codeserver.dev.f8739529-59eb-43bd-8cc4-f6e844f04db4.drush.in >> ~/.ssh/known_hosts
      - name: Checkout server repo
        run: |
          cat ~/.ssh/known_hosts
          git clone ${{ env.DEPLOY_REPO }} ${{ env.DEPLOY_FOLDER }}
          cd ${{ env.DEPLOY_FOLDER }}
          git config user.email "ucomm-devops@stanford.edu"
          git config user.name "devops"

      - name: Sync development repo to server repo
        run: |
          rsync -rpv --delete ${{env.BUILD_FOLDER}}/ ${{env.DEPLOY_FOLDER}} \
            --exclude=.git \
            --exclude=.github \
            --exclude=.gitmodules \
            --exclude=.gitignore \
            --exclude=.htaccess \
            --exclude=.babelrc \
            --exclude=.editorconfig \
            --exclude=.eslintrc \
            --exclude=dev \
            --exclude=dev_components \
            --exclude=docs \
            --exclude=gulp_tasks \
            --exclude=node_modules \
            --exclude=wp-content/plugins/core/assets/templates/cli \
            --exclude=wp-content/mu-plugins/pantheon \
            --exclude=wp-content/mu-plugins/pantheon.php

      - name: Push server repo
        working-directory: ${{ env.DEPLOY_FOLDER }}
        run: |
          echo 'Deploying ${{ github.repository }}, ${{ steps.extract_branch.outputs.branch }} branch, to Pantheon'
          git add -Av
          git commit --allow-empty -m 'Deploy ${{ github.repository }}, ${{ steps.extract_branch.outputs.branch }} branch, to Pantheon'
          git push origin master


      ### Notify Slack

      - name: Slack - success
        if: ${{ success() }}
        uses: tokorom/action-slack-incoming-webhook@v1.1.4
        continue-on-error: true
        with:
          blocks: |
            [
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Status*\n:white_check_mark: Success"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]

      - name: Slack - failure
        if: ${{ failure() }}
        uses: tokorom/action-slack-incoming-webhook@v1.1.4
        continue-on-error: true
        with:
          blocks: |
            [
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Status*\n:x: Failed"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]

      - name: Slack - cancelled
        if: ${{ cancelled() }}
        uses: tokorom/action-slack-incoming-webhook@v1.1.4
        continue-on-error: true
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_WEBHOOK }}
        with:
          blocks: |
            [
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Status*\n:stop: Cancelled"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]
