### Test Slack message formatting

name: Test Slack

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
  
    env:
      INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_WEBHOOK }}

    steps:

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Slack start
        uses: tokorom/action-slack-incoming-webhook@v1.1.4
        with:
          blocks: |
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Deploy to Pantheon"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repo*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch*\n${{ steps.extract_branch.outputs.branch }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Initiated by*\n${{ github.actor }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Initiating event*\n${{ github.event_name }}"
                  }
                ]
              }
            ]

      - name: Slack Success
        uses: tokorom/action-slack-incoming-webhook@v1.1.4
        with:
          blocks: |
            [
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Status*\n:white_check_mark: Success"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]
        if: ${{ success() }}

      - name: Slack Failure
        uses: tokorom/action-slack-incoming-webhook@v1.1.4
        with:
          blocks: |
            [
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Status*\n:x: Failed"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]
        if: ${{ failure() }}

      - name: Slack Cancelled
        uses: tokorom/action-slack-incoming-webhook@v1.1.4
        with:
          blocks: |
            [
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Status*\n:stop: Cancelled"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]
        if: ${{ cancelled() }}
