### Test Slack message formatting

name: Test Slack

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
  
    env:
      INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_WEBHOOK }}

    steps:

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Slack msg 1
        uses: tokorom/action-slack-incoming-webhook@v1.1.4
        with:
          blocks: |
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Deploy to Pantheon",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repo*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch*\n${{ steps.extract_branch.outputs.branch }}"
                  }
                ]
              }
            ]
